#[macro_use]
extern crate foundry_test_utils;
mod alphanet;
mod bind_json;
mod build;
mod build_revive;
mod cache;
mod cmd;
mod compiler;
mod config;
pub mod constants;
mod context;
mod coverage;
mod create;
mod debug;
mod doc;
mod eip712;
mod ext_integration;
mod geiger;
mod inline_config;
mod multi_script;
mod script;
mod soldeer;
mod svm;
mod test_cmd;
pub mod utils;
mod verify;
mod verify_bytecode;
